require 'build/src/app/routes/account-password'
require 'build/src/app/routes/account-profile'
require 'build/src/app/routes/application'
require 'build/src/app/routes/authenticated'
require 'build/src/app/routes/authentication'
require 'build/src/app/routes/logout'
require 'build/src/app/routes/user'
require 'build/src/app/routes/users-new'
require 'build/src/app/routes/users'

require 'build/src/app/routes/page'
