require 'build/src/widgets/views/app'
require 'build/src/widgets/views/sidebar'
require 'build/src/widgets/views/list'
require 'build/src/widgets/views/select2'
require 'build/src/widgets/views/tagging-select2'
